### ISSUE TITLE
Sort-object-props should ignore spread

### ISSUE THREAD

**Issue by guyfedwards** [JamieMason/codemods#2]
When an object has keys spread it should only sort either side of the spread, not moving keys across spread boundary.

Spread is often used for overrides or defaults and so moving across spread boundary can cause bugs.

See [this comment](https://github.com/eslint/eslint/issues/10715#issuecomment-409745176)

```JavaScript
const o = {
  d,
  b,
  ...other,
  c,
  a
};
```
can ONLY be safely autofixed to:

```JavaScript
const o = {
  b,
  d,
  ...other,
  a,
  c
};
```

Probably should be the same for jsx props

**Comment by JamieMason** [comment]
Thanks a lot @guyfedwards you're exactly right, this will need addressing 👍

**Comment by JamieMason** [comment]
I eventually got around to this. Note to self, the script I developed against was:

```js
const e = 'E';
const c = 'C';

const other = {
  d: 'D',
  e: 'A',
  [c]: 1
};

const sortMe = {
  c,
  b: 'B',
  ...other,
  [e]: 1,
  d: 'D',
  [c]: 1,
  a: 'A',
  ...other,
  ...other,
  f: 'E',
  g: 'G',
  ...other
};
```

EDIT: and for JSX against:

```jsx
import React from 'react';

const Component = props => (
  <div>
    <div e="A" d="D" />
    <div c b="B" {...props} d="D" a="A" {...props} {...props} f="E" g="G" {...props} />
  </div>
);
```
